name: Docker

on:
    push:
        branches:
            - "master"
        tags:
            - "v*.*.*"
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    docker:
        runs-on: docker
        container:
            image: ghcr.io/catthehacker/ubuntu:act-latest
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: forgejo.clowdertech.com
                  username: Bearer
                  password: ${{ secrets.ACTIONS_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: forgejo.clowdertech.com/${{ github.repository }}:${{ github.ref_name }}
